// ─── AntSeed Model Marketplace Adapter ───────────────────────────────
// Comprehensive catalog of decentralized AI model hosts & metered inference options.
// Foundation: Decentralized AI model hosts (Dolphin, DeepSeek R1, Llama 3.3, Qwen 2.5, Mistral, Nous Hermes).
// ─────────────────────────────────────────────────────────────────────

export interface AntSeedModel {
  id: string;
  name: string;
  provider: string;
  category: 'reasoning' | 'coding' | 'research' | 'writing' | 'image' | 'enterprise' | 'general';
  description: string;
  capabilities: string[];
  contextWindow: number; // in tokens
  priceInputPerMillion: number; // $ per 1M input tokens
  priceOutputPerMillion: number; // $ per 1M output tokens
  isFree: boolean;
  speed: 'Ultra Fast' | 'Fast' | 'Balanced' | 'Deep Reasoning';
  latencyMs: number;
  reliabilityPercent: number;
  privacy: 'Zero-Log' | 'Encrypted Enterprise' | 'Standard Community';
  supportedInputs: Array<'text' | 'image' | 'code' | 'document' | 'audio'>;
  trustScore: number; // 0 - 100
  rating: number; // 0 - 5.0
  availability: 'online' | 'degraded' | 'maintenance';
  badge?: string;
  hostType: 'decentralized-host' | 'open-weights-node' | 'workflow-connector';
}

export const ANTSEED_MODEL_CATALOG: AntSeedModel[] = [
  {
    id: 'dolphin-mixtral-8x7b-free',
    name: 'Dolphin 8x7B (Uncensored)',
    provider: 'Dolphin Open Intelligence',
    category: 'general',
    description: 'Completely free, open-weights conversational reasoning model for all Nexus users.',
    capabilities: ['General Chat', 'Creative Writing', 'Code Generation', 'Brainstorming'],
    contextWindow: 32768,
    priceInputPerMillion: 0.0,
    priceOutputPerMillion: 0.0,
    isFree: true,
    speed: 'Ultra Fast',
    latencyMs: 120,
    reliabilityPercent: 99.9,
    privacy: 'Zero-Log',
    supportedInputs: ['text', 'code'],
    trustScore: 99,
    rating: 4.8,
    availability: 'online',
    badge: 'FREE UNLIMITED',
    hostType: 'decentralized-host',
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1 Reasoning Host',
    provider: 'DeepSeek (via AntSeed Decentralized Node)',
    category: 'reasoning',
    description: 'Open-weights reasoning host with explicit step-by-step chain of thought math & code logic.',
    capabilities: ['Chain-of-Thought', 'Advanced Math', 'Algorithmic Logic', 'Cost-Efficient'],
    contextWindow: 64000,
    priceInputPerMillion: 0.55,
    priceOutputPerMillion: 2.19,
    isFree: false,
    speed: 'Balanced',
    latencyMs: 340,
    reliabilityPercent: 99.7,
    privacy: 'Zero-Log',
    supportedInputs: ['text', 'code'],
    trustScore: 98,
    rating: 4.92,
    availability: 'online',
    badge: 'MOST POPULAR',
    hostType: 'decentralized-host',
  },
  {
    id: 'llama-3-3-70b',
    name: 'Llama 3.3 70B Instruct',
    provider: 'Meta AI (via AntSeed Node Network)',
    category: 'research',
    description: 'Open flagship model host delivering GPT-4 class performance at extremely competitive pricing.',
    capabilities: ['Knowledge Retrieval', 'Text Synthesis', 'Open Weights', 'Fast Output'],
    contextWindow: 128000,
    priceInputPerMillion: 0.7,
    priceOutputPerMillion: 0.9,
    isFree: false,
    speed: 'Ultra Fast',
    latencyMs: 180,
    reliabilityPercent: 99.9,
    privacy: 'Zero-Log',
    supportedInputs: ['text', 'code'],
    trustScore: 97,
    rating: 4.88,
    availability: 'online',
    badge: 'TOP RATED',
    hostType: 'open-weights-node',
  },
  {
    id: 'qwen-2-5-72b',
    name: 'Qwen 2.5 72B Coding Host',
    provider: 'Alibaba Cloud (via AntSeed Node Network)',
    category: 'coding',
    description: 'Specialized open-weights coding model host for multi-language refactoring and architecture.',
    capabilities: ['Code Synthesis', 'Bug Fixing', 'TypeScript/Python', 'JSON Schema'],
    contextWindow: 128000,
    priceInputPerMillion: 0.6,
    priceOutputPerMillion: 1.2,
    isFree: false,
    speed: 'Fast',
    latencyMs: 210,
    reliabilityPercent: 99.6,
    privacy: 'Zero-Log',
    supportedInputs: ['text', 'code', 'document'],
    trustScore: 96,
    rating: 4.86,
    availability: 'online',
    badge: 'BEST FOR CODE',
    hostType: 'open-weights-node',
  },
  {
    id: 'nous-hermes-3-70b',
    name: 'Nous Hermes 3 70B',
    provider: 'Nous Research Decentralized Node',
    category: 'reasoning',
    description: 'Advanced agentic steering and multi-turn instruction following open weights host.',
    capabilities: ['Agentic Planning', 'Tool Calling', 'Instruction Following', 'Function Exec'],
    contextWindow: 128000,
    priceInputPerMillion: 0.8,
    priceOutputPerMillion: 1.6,
    isFree: false,
    speed: 'Fast',
    latencyMs: 250,
    reliabilityPercent: 99.5,
    privacy: 'Zero-Log',
    supportedInputs: ['text', 'code'],
    trustScore: 96,
    rating: 4.84,
    availability: 'online',
    badge: 'AGENTIC AI',
    hostType: 'decentralized-host',
  },
  {
    id: 'mistral-large-2',
    name: 'Mistral Large 2 Host',
    provider: 'Mistral Open AI Network',
    category: 'enterprise',
    description: 'Enterprise-grade European multilingual model host with advanced function calling & precision.',
    capabilities: ['Multilingual', 'Function Calling', 'EU Compliance', 'Enterprise SLA'],
    contextWindow: 128000,
    priceInputPerMillion: 2.0,
    priceOutputPerMillion: 6.0,
    isFree: false,
    speed: 'Fast',
    latencyMs: 260,
    reliabilityPercent: 99.8,
    privacy: 'Encrypted Enterprise',
    supportedInputs: ['text', 'code', 'document'],
    trustScore: 97,
    rating: 4.82,
    availability: 'online',
    badge: 'ENTERPRISE',
    hostType: 'open-weights-node',
  },
  {
    id: 'flux-1-1-pro',
    name: 'Flux 1.1 Pro Image Engine',
    provider: 'Black Forest Labs',
    category: 'image',
    description: 'State-of-the-art photorealistic image synthesis, typography rendering, and UI graphics.',
    capabilities: ['Image Generation', 'Typography', 'UI Layout Design', 'Photorealism'],
    contextWindow: 4096,
    priceInputPerMillion: 4.0,
    priceOutputPerMillion: 4.0,
    isFree: false,
    speed: 'Fast',
    latencyMs: 1400,
    reliabilityPercent: 99.2,
    privacy: 'Standard Community',
    supportedInputs: ['text', 'image'],
    trustScore: 95,
    rating: 4.91,
    availability: 'online',
    badge: 'IMAGE AI',
    hostType: 'decentralized-host',
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet (Workflow Connector)',
    provider: 'Anthropic (External Step Connector)',
    category: 'enterprise',
    description: 'Optional external model connector for complex multi-step workflow review pipelines.',
    capabilities: ['Workflow Verification', 'Refactored Code', 'Document Analysis'],
    contextWindow: 200000,
    priceInputPerMillion: 3.0,
    priceOutputPerMillion: 15.0,
    isFree: false,
    speed: 'Fast',
    latencyMs: 380,
    reliabilityPercent: 99.8,
    privacy: 'Encrypted Enterprise',
    supportedInputs: ['text', 'code', 'image', 'document'],
    trustScore: 98,
    rating: 4.95,
    availability: 'online',
    badge: 'WORKFLOW CONNECTOR',
    hostType: 'workflow-connector',
  },
];
