// ─── AntSeed Model Marketplace Adapter ───────────────────────────────
// Comprehensive catalog of free & paid AI models with pricing, latency, & trust metadata.
// ─────────────────────────────────────────────────────────────────────

export interface AntSeedModel {
  id: string;
  name: string;
  provider: string;
  category: 'reasoning' | 'coding' | 'research' | 'writing' | 'image' | 'enterprise' | 'general';
  description: string;
  capabilities: string[];
  contextWindow: number; // in tokens
  priceInputPerMillion: number; // $ per 1M input tokens
  priceOutputPerMillion: number; // $ per 1M output tokens
  isFree: boolean;
  speed: 'Ultra Fast' | 'Fast' | 'Balanced' | 'Deep Reasoning';
  latencyMs: number;
  reliabilityPercent: number;
  privacy: 'Zero-Log' | 'Encrypted Enterprise' | 'Standard Community';
  supportedInputs: Array<'text' | 'image' | 'code' | 'document' | 'audio'>;
  trustScore: number; // 0 - 100
  rating: number; // 0 - 5.0
  availability: 'online' | 'degraded' | 'maintenance';
  badge?: string;
}

export const ANTSEED_MODEL_CATALOG: AntSeedModel[] = [
  {
    id: 'dolphin-mixtral-8x7b-free',
    name: 'Dolphin 8x7B (Uncensored)',
    provider: 'Dolphin Open Intelligence',
    category: 'general',
    description: 'Completely free, open-weights conversational reasoning model for all Nexus users.',
    capabilities: ['General Chat', 'Creative Writing', 'Code Generation', 'Brainstorming'],
    contextWindow: 32768,
    priceInputPerMillion: 0.0,
    priceOutputPerMillion: 0.0,
    isFree: true,
    speed: 'Ultra Fast',
    latencyMs: 120,
    reliabilityPercent: 99.9,
    privacy: 'Zero-Log',
    supportedInputs: ['text', 'code'],
    trustScore: 99,
    rating: 4.8,
    availability: 'online',
    badge: 'FREE UNLIMITED',
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic (via AntSeed)',
    category: 'reasoning',
    description: 'Industry-leading frontier reasoning, complex coding, and structured workflow analysis.',
    capabilities: ['Complex Reasoning', 'Refactored Code', 'JSON Extraction', 'Document Analysis'],
    contextWindow: 200000,
    priceInputPerMillion: 3.0,
    priceOutputPerMillion: 15.0,
    isFree: false,
    speed: 'Fast',
    latencyMs: 380,
    reliabilityPercent: 99.8,
    privacy: 'Encrypted Enterprise',
    supportedInputs: ['text', 'code', 'image', 'document'],
    trustScore: 98,
    rating: 4.95,
    availability: 'online',
    badge: 'MOST POPULAR',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o Omni',
    provider: 'OpenAI (via AntSeed)',
    category: 'general',
    description: 'High-speed multimodal intelligence across text, vision, and advanced reasoning.',
    capabilities: ['Multimodal Vision', 'Data Analysis', 'Fast Inference', 'Multilingual'],
    contextWindow: 128000,
    priceInputPerMillion: 2.5,
    priceOutputPerMillion: 10.0,
    isFree: false,
    speed: 'Ultra Fast',
    latencyMs: 220,
    reliabilityPercent: 99.7,
    privacy: 'Encrypted Enterprise',
    supportedInputs: ['text', 'code', 'image'],
    trustScore: 97,
    rating: 4.9,
    availability: 'online',
    badge: 'TOP RATED',
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1 Reasoning',
    provider: 'DeepSeek (via AntSeed)',
    category: 'reasoning',
    description: 'Open-weights reasoning model with explicit step-by-step chain of thought math & code logic.',
    capabilities: ['Chain-of-Thought', 'Advanced Math', 'Algorithmic Logic', 'Cost-Efficient'],
    contextWindow: 64000,
    priceInputPerMillion: 0.55,
    priceOutputPerMillion: 2.19,
    isFree: false,
    speed: 'Balanced',
    latencyMs: 540,
    reliabilityPercent: 99.5,
    privacy: 'Zero-Log',
    supportedInputs: ['text', 'code'],
    trustScore: 96,
    rating: 4.88,
    availability: 'online',
    badge: 'HIGH VALUE',
  },
  {
    id: 'llama-3-3-70b',
    name: 'Llama 3.3 70B Instruct',
    provider: 'Meta AI (via AntSeed)',
    category: 'research',
    description: 'Open flagship model delivering GPT-4 class performance at extremely competitive pricing.',
    capabilities: ['Knowledge Retrieval', 'Text Synthesis', 'Open Weights', 'Fast Output'],
    contextWindow: 128000,
    priceInputPerMillion: 0.7,
    priceOutputPerMillion: 0.9,
    isFree: false,
    speed: 'Ultra Fast',
    latencyMs: 180,
    reliabilityPercent: 99.9,
    privacy: 'Zero-Log',
    supportedInputs: ['text', 'code'],
    trustScore: 97,
    rating: 4.85,
    availability: 'online',
  },
  {
    id: 'gemini-2-5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google DeepMind (via AntSeed)',
    category: 'general',
    description: '1M token context window for massive repository processing, video analysis, and speed.',
    capabilities: ['1M Token Context', 'Video & Audio', 'Fast Search', 'Document Audit'],
    contextWindow: 1000000,
    priceInputPerMillion: 0.15,
    priceOutputPerMillion: 0.6,
    isFree: false,
    speed: 'Ultra Fast',
    latencyMs: 160,
    reliabilityPercent: 99.9,
    privacy: 'Encrypted Enterprise',
    supportedInputs: ['text', 'code', 'image', 'document', 'audio'],
    trustScore: 98,
    rating: 4.92,
    availability: 'online',
    badge: '1M CONTEXT',
  },
  {
    id: 'flux-1-1-pro',
    name: 'Flux 1.1 Pro Image Engine',
    provider: 'Black Forest Labs',
    category: 'image',
    description: 'State-of-the-art photorealistic image synthesis, typography rendering, and UI graphics.',
    capabilities: ['Image Generation', 'Typography', 'UI Layout Design', 'Photorealism'],
    contextWindow: 4096,
    priceInputPerMillion: 4.0, // $0.04 per image
    priceOutputPerMillion: 4.0,
    isFree: false,
    speed: 'Fast',
    latencyMs: 1400,
    reliabilityPercent: 99.2,
    privacy: 'Standard Community',
    supportedInputs: ['text', 'image'],
    trustScore: 95,
    rating: 4.91,
    availability: 'online',
    badge: 'IMAGE AI',
  },
  {
    id: 'mistral-large-2',
    name: 'Mistral Large 2',
    provider: 'Mistral AI',
    category: 'enterprise',
    description: 'Enterprise-grade European multilingual model with advanced function calling & precision.',
    capabilities: ['Multilingual', 'Function Calling', 'EU Compliance', 'Enterprise SLA'],
    contextWindow: 128000,
    priceInputPerMillion: 2.0,
    priceOutputPerMillion: 6.0,
    isFree: false,
    speed: 'Fast',
    latencyMs: 260,
    reliabilityPercent: 99.8,
    privacy: 'Encrypted Enterprise',
    supportedInputs: ['text', 'code', 'document'],
    trustScore: 97,
    rating: 4.82,
    availability: 'online',
  },
];
